# Generated by Django 3.2.4 on 2021-10-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='-', max_length=100)),
                ('section', models.CharField(default='-', max_length=50)),
                ('position', models.CharField(default='-', max_length=50)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('drawing_no', models.CharField(default='-', max_length=20)),
                ('fg_code', models.CharField(default='-', max_length=20)),
                ('emp_id', models.CharField(default='-', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('emp_id', models.CharField(default='-', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pptapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.CharField(default='-', max_length=20)),
                ('location', models.CharField(default='-', max_length=100)),
                ('status', models.CharField(default='-', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pptapp.order')),
            ],
        ),
    ]
