# Generated by Django 3.1.3 on 2021-10-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serial',
            name='code',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
