# Generated by Django 3.1.3 on 2021-10-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0003_remove_serial_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pptapp.serial'),
        ),
    ]
