# Generated by Django 3.2.4 on 2022-01-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0004_auto_20211017_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='po_no',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
