# Generated by Django 3.2.4 on 2022-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0005_serial_po_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_code', models.CharField(default='-', max_length=20)),
                ('old_order_no', models.CharField(default='-', max_length=20)),
                ('new_order_no', models.CharField(default='-', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
