# Generated by Django 3.2.4 on 2022-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0006_movehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='movehistory',
            name='emp_id',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='movehistory',
            name='reason',
            field=models.TextField(default='-', max_length=500),
        ),
    ]
