# Generated by Django 3.2.4 on 2023-04-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pptapp', '0007_serial_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serial',
            name='type',
        ),
    ]
